### ISSUE TITLE
[BUG] Virtual furnace cooks but fire icon and the arrow is not shown + an error thrown in the console

### ISSUE THREAD

**Issue by alaajel** [ShaneBeeStudios/VirtualFurnace#2]
**Describe the bug**
When the furnace cooks it does successfully but there is no fire 
![image](https://user-images.githubusercontent.com/34905970/134710538-dd7a8e58-ff05-4d14-8de4-8b05d654f4d2.png)

**To Reproduce**
create a furnace and show it to the player
and tick it
results no arrows and fire show up with error in the console 
but item still get cooked.
```
[20:35:50 WARN]: [SomePlugin] Plugin SomePlugin v1.0-SNAPSHOT generated an exception while executing task 6
java.lang.IndexOutOfBoundsException: Index 2 out of bounds for length 0
        at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
        at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
        at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
        at java.util.Objects.checkIndex(Objects.java:359) ~[?:?]
        at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
        at net.minecraft.world.inventory.AbstractContainerMenu.setData(AbstractContainerMenu.java:744) ~[app:?]
        at org.bukkit.craftbukkit.v1_17_R1.entity.CraftPlayer.setWindowProperty(CraftPlayer.java:1826) ~[patched_1.17.1.jar:git-Purpur-1310]
        at org.bukkit.inventory.InventoryView.setProperty(InventoryView.java:446) ~[patched_1.17.1.jar:git-Purpur-1310]
        at net.glomc.backpack.virtualfurnace.api.machine.Furnace.updateInventoryView(Furnace.java:220) ~[SomePlugin-1.0-SNAPSHOT.jar:?]
        at net.glomc.backpack.virtualfurnace.api.machine.Furnace.tick(Furnace.java:254) ~[SomePlugin-1.0-SNAPSHOT.jar:?]        at net.glomc.fun_plugins.someplugin.SomePlugin$1.run(SomePlugin.java:49) ~[SomePlugin-1.0-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Purpur-1310]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Purpur-1310]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Purpur-1310]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Expected behavior**
it should show the progress and the fire

**Version Info:**
 - **Plugin Version:** 1.0.0-Beta12
 - **Server Version/Platform** Paper 1.17.1, paper 1.17 , Purpur 1.17.1

**Additional context**
nothing

**Comment by ShaneBeee** [comment]
This is a known issue and has been fixed in https://github.com/ShaneBeeStudios/VirtualFurnace/commit/311a276292ed10587420702291a5d0a13c64d309

I have not been able to successfully upload/deploy to the maven repo (still need to figure out why I can't) but you can build/install the maven repo locally to implement this fix in your project, just use version 1.0.0-Beta12

**Comment by alaajel** [comment]
thats what i have done still happening?

**Comment by ShaneBeee** [comment]
Im not exactly sure what you've done, but if you clone this repo to your machine, run `mvn install`, then in your project, update to beta12, it should work correctly.
I have done this in the testing and it seems to work fine

**Comment by alaajel** [comment]
it was using beta11 btw ignore above reply that i have made anyways
thanks for help, and oh about the maven issue you got maybe worth checking your maven publishing credentials?

**Comment by ShaneBeee** [comment]
> and oh about the maven issue you got maybe worth checking your maven publishing credentials?

Thanks, since I last did it, I reformatted my computer, so I had to redo my credentials. For some reason the FTP system is not working, even trying to use FileZilla its not working. 

I'm going to keep checking, I'm sure I did something silly and hopefully I can figure it out soon

**Comment by ShaneBeee** [comment]
update:
I have successfully deployed beta12 to the maven repo
